name: Publish build to public repository

on:
  workflow_call:
    inputs:
      userid:
        required: true
        type: string
      username:
        required: true
        type: string
      email:
        required: true
        type: string
      public-repo:
        required: true
        type: string
    secrets:
      GIT_TOKEN:
        required: true

jobs:
  build:
    name: "Build & Deploy"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # build environment - Node
    - name: Install node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        
    # NPM task
    - run: npm i
      name: install dependencies
      
    - run: npm run build --if-present
      name: build
      
    # Git task

    # remove git history and settings - to avoid inheritance
    - run: rm -rf .git

    # re-initialise git
    - run: git init -b main
    - run: git config user.name "${{ inputs.username }}"
    - run: git config user.email "${{ inputs.email }}"

    # configure the repository to the remote
    - run: git config --local remote.origin.url https://${{ inputs.userid }}:${{ secrets.GIT_TOKEN }}@github.com/ketl/${{ inputs.public-repo }}.git
    - run: git config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    - run: git config --local branch.main.remote origin
    - run: git config --local branch.main.merge refs/heads/main
    
    # add and commit /docs/ folder
    - run: git add docs
    
    # debug
    - run: git config --list

    - run: git commit -m "deploy the bundle"
    
    # push the commit to the public repository
    - run: git push origin HEAD:main --force
